os: linux
dist: xenial
language: python

addons:
  apt:
    packages:
      umockdev

python:
- 3.5

install:
- pip install "setuptools>=36.3" -r test-requirements.txt

script:
- pytest

after_success:
- codecov
