os: linux
dist: xenial
language: python

addons:
  apt:
    packages:
      umockdev

python:
- 3.4
- 3.5
- 3.6
- 3.7

install:
- pip install "setuptools>=36.3" -r test-requirements.txt

script:
- pytest -vs
